up

diff --git a/agilite/distum/.function/init-h256 b/agilite/distum/.function/init-h256
--- a/agilite/distum/.function/init-h256
+++ b/agilite/distum/.function/init-h256
@@ -7,14 +7,14 @@ YSON_H256=.pfi/h256.yson.yaml
 
 
 PFI_ID=$(.function/part-guid.ps1 $PFI_DRIVE)
-test -z "$PFI_ID" && PFI_ID=$(.function/part-id.ps1 $PFI_DRIVE)
+test -z "$PFI_ID" && echo "PFI ID not found" && exit 1
 echo "PFI ID: $PFI_ID"
 
 cd $PFI_DRIVE
 mkdir -p .pfi
 test -s $PFI_SUBFILTER || echo ".pfi|-" > $PFI_SUBFILTER
 
-rm $LIST_tmp
+rm $LIST_tmp $YSON_H256
 while read line ; do
   PFI_subdir=$(echo $line | awk -F '\\|-' '{print $1}')
   PFI_filter=$(echo $line | awk -F'\\|-'    '{ for (i=2; i<= NF; i++) {printf "%s ",$i} }'  )
@@ -27,11 +27,14 @@ done < $PFI_SUBFILTER
 
 
 echo "Building space H256"
-sed -i   -e 's/^/\"/' -e 's/$/\" /' $LIST_tmp
 
-bash -c "sha256sum  $(echo $(< $LIST_tmp)) > $YSON_H256 2>/dev/null"
+while IFS= read -r  item ; do
+	sha256sum "$item" >> $YSON_H256 
+done < $LIST_tmp
+
 sed -i \
-    -e "s/ \*/: {\"pfi\":[\"$PFI_ID\//" \
+    -e "s/  /: {\"pfi\":[\"$PFI_ID\//" \
     -e 's/$/"]}/' \
     $YSON_H256
+
 find $(readlink -f .pfi) -type f
