gedrive: rename

diff --git a/agilite/gedrive/.function/rename b/agilite/gedrive/.function/rename
--- a/agilite/gedrive/.function/rename
+++ b/agilite/gedrive/.function/rename
@@ -1,10 +1,9 @@
-#!/bin/bash -e
+#!/bin/bash
 
 source .function/rcloner
 
 SUB_PATH=$1
 NEW_NAME=$2
-EXTENT=$(basename $(grep -l  $SUB_PATH $META_DIR/*  | head -1)  2>/dev/null)
 
 function abort(){
     local msg=$1
@@ -12,12 +11,26 @@ function abort(){
     exit 1
 }
 
-rclone ls ${EXTENT}${SUB_PATH} &>/dev/null || abort "SOURCE IS NOT EXISTING"
-rclone ls ${EXTENT}$(dirname $SUB_PATH)/${NEW_NAME} &>/dev/null  &&  abort "DEST IS EXISTING ALREADY"
+test -z "$SUB_PATH" && abort "SUB_PATH missing"
+test -z "$NEW_NAME" && abort "NEW_NAME missing"
+PARENT_SUB_PATH=$(dirname $SUB_PATH)
+NEW_SUB_PATH="${PARENT_SUB_PATH}/${NEW_NAME}"
+[[ "$PARENT_SUB_PATH" == "." ]] && NEW_SUB_PATH="${NEW_NAME}"
 
-rclone moveto ${EXTENT}${SUB_PATH}    ${EXTENT}$(dirname $SUB_PATH)/${NEW_NAME}
-rclone ls $EXTENT > $META_DIR/$EXTENT
 
-echo "SUBPATH RENAMED |RN|" 
-echo "${EXTENT}$(dirname $SUB_PATH)/${NEW_NAME}"
+TARGET_EXTENT=$(grep -l  "^[ 0-9]\+$SUB_PATH" $META_DIR/* | xargs -I {} basename {})
+
+for EXTENT in $TARGET_EXTENT ; do
+    if ! rclone ls ${EXTENT}${SUB_PATH} &>/dev/null ; then
+        echo  "${EXTENT}${SUB_PATH} IS NOT EXISTING" && continue
+    fi
+
+    if rclone ls ${EXTENT}${NEW_SUB_PATH} &>/dev/null ; then
+        echo "${EXTENT}${NEW_SUB_PATH} IS EXISTING ALREADY" && continue
+    fi
+    rclone moveto ${EXTENT}${SUB_PATH}    ${EXTENT}${NEW_SUB_PATH}
+    rclone ls $EXTENT > $META_DIR/$EXTENT
+    echo "SUBPATH RENAMED |RN|"
+    echo "${EXTENT}${NEW_SUB_PATH}"
+done
 
